Listen 9001

<VirtualHost *:9001>
      ServerAdmin bt@geo.sm
      
      DocumentRoot /var/www/html/ifdd-frontend/dist/ifdd/
      <Directory /var/www/html/ifdd-frontend/dist/ifdd/>
              Options Indexes FollowSymLinks
              AllowOverride All
              allow from all
              Require all granted
      </Directory>
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>