Listen 9000
<VirtualHost *:9000>
      ServerAdmin bt@geo.sm
     
      
      DocumentRoot /var/www/html/ifdd-services/public/
      <Directory /var/www/html/ifdd-services/public/>
              Options Indexes FollowSymLinks
              AllowOverride All
              allow from all
              Require all granted
      </Directory>
      ErrorLog ${APACHE_LOG_DIR}/error.log
      CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>